### PR TITLE
Update's the weather script for every 15 mins

### PR DESCRIPTION
**Pull request by krushil1**

### CODE REVIEW

**Comment by lukelmg** [comment]
looks good!

**Comment by lukelmg** [comment]
wait maybe not lol

**Comment by lukelmg** [comment]
there's something weird with the fetch command and the async function. I'm not sure what the issue is.

**Comment by krushil1** [comment]
Umm, what's happening?

**Comment by lukelmg** [comment]
Hey Krushil, check out the latest commit. It used to work but your latest pull request messed up the weather somehow. I keep getting this error: 
image

**Comment by krushil1** [comment]
I will check it out soon and hope I can figure it out!!!

**Comment by krushil1** [comment]
So after investigating a bit, I made it work again! Submitting a PR either today or tomorrow morning! 
Screen Shot 2021-08-02 at 11 57 14 PM

**Pull request closed without merging**
